### ISSUE TITLE
Type up requirements issue for Zoom fixes

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyterlab-accessible-themes#34]
From #11 #16 #18 #12 #14 

- Review the findings
- Turn the findings + recommendations into concrete actions/tasks
- Assign ticket and work on

**Comment by steff456** [comment]
This is a summary of the Zoom audit in the latest Jupyterlab interface

# Referenced issues
- [Left sidebar audit](https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/3)
- [Right sidebar audit](https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/6)
- [Main content area audit](https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/9)
- [Menu bar audit](https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/11)
- [Context menu audit](https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/14)
- [Settings audit](https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/16)
- [Status bar audit](https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/18)

# Findings
- The definition of vertical padding and height are working as they are and they have sense to leave them in px in the **sidebars** items.
- We need to define a new UX for when the left sidebar is taking too much space compared to the main area. My suggestion will be to compress the left pane to give priority to the main content area.
- Files in the main content area are wrapping lines instead of having a horizontal scrollbar, which allows to see all the code without any action.
- If zoom is activated some filenames are not visible in the tabs, but hovering over them will give the complete information of the file
- Opening a lot of files in zoom may cause to just seeing the icon and not being able to even close it
- The notebook's toolbar is responsive and all the options are visible and usable
- Cell options layout breaks with 400% zoom
- Python logo in the launcher pixelates with zoom
- Dialogs occupy the complete interface with 400% zoom
- The menu items start getting lost as zoom increases
- The dropdown menus are not visible or usable with 400% zoom
- Modifying to responsive layouts break the menubar and its usability
- Automatically we have a scrollbar to navigate through the options in context menus if not visible at first
- The size of context menus is fixed in px which occupy a lot of space in small screens or high zoom
- Settings is not usable in small screens or with zoom, the options are chopped and not readable
- Settings left menu area doesn't resize
- Settings is using the same `gear` icon for multiple entries
- The Status bar is responsive for even mobile screen sizes

# General questions
- Do we want to support changes in the default text size of the browser? This will affect all the UI and right now it is using the minimum text size set in the settings of the browser.
- Do we want the dialogs to occupy and block the complete interface when zoom is high?
- Accessibility guidelines support the idea to have a button for context menus, do we want to follow it?
- The same `gear` icon in multiple entries of the Settings pane is intentional?

# Tasks
- [ ] Define a new UX for the **left** sidebar when they are taking too much space compared to the main area
- [ ] Define a new UX for the **right** sidebar when they are taking too much space compared to the main area
- [ ] Define a new UX/UI for the tabs in the main content area, especially the cases where too many of them are opened.
- [ ] Make the cell options layout be responsive (it may include removing some options or adding ellipsis when the space is small)
- [ ] Change the python logo to a new image that has better resolution
- [ ] Dialogs sizes need to be checked for high zoom or small screens
- [ ] Add a hamburger menu in the main menu bar when the space is smaller to avoid loosing items. 
- [ ] Dropdown menus from the main menu bar should open to the left/right depending on the space in the screen
- [ ] Check and define the UI/UX for context menus in small screens and/or high zoom
- [ ] Define a new UX for the Settings pane to handle small screens and/or high zoom

For more info about each pane please see its particular issue where screenshots and more notes are described.

**Comment by gabalafou** [comment]
Thanks for summarizing this!

I have some thoughts and comments about the above which I will cover in no particular order, one quoted line at a time.

> If zoom is activated some filenames are not visible in the tabs, but hovering over them will give the complete information of the file

I could check on my Windows laptop to see what happens in similar situations on Windows if you like.

> Do we want the dialogs to occupy and block the complete interface when zoom is high?

Ditto, could check something similar on Windows.

> The menu items start getting lost as zoom increases

Ditto, could check on Windows.

For the preceding issues, 

> Accessibility guidelines support the idea to have a button for context menus, do we want to follow it?

Can you show an example of this, a button for context menus?

> Settings left menu area doesn't resize

I think I was able to resize settings left menu on mine. I can show in tomorrow's call.

>  Settings is not usable in small screens or with zoom, the options are chopped and not readable

Good catch on the Settings Editor. I imagine that our planned extension will need to make use of the Settings Editor. On my dev machine, which has a pretty high resolution (3072 × 1920), it starts to get hard to use at around 150% zoom in Chrome. 

> Modifying to responsive layouts break the menubar and its usability

I'm not sure what you mean by responsible layout breaking the menubar. Also not sure about your comment about the status bar and responsiveness. Perhaps we could cover this in the team call.

**Comment by isabela-pf** [comment]
Thanks for giving such thorough review and compiling your findings, @steff456! This is so pleasantly skimmable so I can figure out the best places to dive in with the more focused issues.

I'm not sure how much this comment will help, but I do want to say I think all your findings and tasks make sense to me. I think the following apply to me immediately

> - [ ] Define a new UX for the **left** sidebar when they are taking too much space compared to the main area
> - [ ] Define a new UX for the **right** sidebar when they are taking too much space compared to the main area
> - [ ] Define a new UX/UI for the tabs in the main content area, especially the cases where too many of them are opened.
> - [ ] Make the cell options layout be responsive (it may include removing some options or adding ellipsis when the space is small)
> - [ ] ~~Dialogs sizes need to be checked for high zoom or small screens~~ recommendations for dialogs in small areas
> - [ ] Dropdown menus from the main menu bar should open to the left/right depending on the space in the screen
> - [ ] Check and define the UI/UX for context menus in small screens and/or high zoom
> - [ ] Define a new UX for the Settings pane to handle small screens and/or high zoom

Does that sound correct? 

I've been looking into patterns for zoom behavior and small screens in tandem. Zoom is an areas I've worked on less, so I think I'm still synthesizing the info I've gathered there. 

I think my direct next step is to provide a low-fidelity visual and pattern for how each content area (from what you've listed) behaves in 
1. a small screen (roughly mobile device sized) 
2. a larger screen at 400% zoom (roughly laptop sized)
3. the ways they overlap/interact

**Comment by steff456** [comment]
> Does that sound correct?

Yes, it sounds like a good plan :)

**Comment by trallard** [comment]
## Questions to dive into

> If zoom is activated some filenames are not visible in the tabs, but hovering over them will give the complete information of the file

> Do we want to support changes in the default text size of the browser? This will affect all the UI and right now it is using the minimum text size set in the settings of the browser.

> Do we want the dialogs to occupy and block the complete interface when zoom is high?

> Accessibility guidelines support the idea to have a button for context menus, do we want to follow it?

> The same gear icon in multiple entries of the Settings pane is intentional?

> Settings is not usable in small screens or with zoom, the options are chopped and not readable

@isabela-pf  will work on:

- [ ] Define a new UX for the left sidebar when they are taking too much space compared to the main area
- [ ] Define a new UX for the right sidebar when they are taking too much space compared to the main area
- [ ]  Define a new UX/UI for the tabs in the main content area, especially the cases where too many of them are opened.
- [ ] Make the cell options layout be responsive (it may include removing some options or adding ellipsis when the space is small)
- [ ]  Dropdown menus from the main menu bar should open to the left/right depending on the space in the screen
- [ ] Check and define the UI/UX for context menus in small screens and/or high zoom
- [ ] Define a new UX for the Settings pane to handle small screens and/or high zoom
- [ ] Dialogs sizes need to be checked for high zoom or small screens

@steff456 
- [ ] Change the python logo to a new image that has better resolution


TBD
- [ ] Add a hamburger menu in the main menu bar when the space is smaller to avoid loosing items.
- [ ] Need to add this audit and findings to the jupyter/accessibility repo

**Comment by gabalafou** [comment]
One question all of this raises for me: should we say that we won't support screens below a certain width?

**Comment by gabalafou** [comment]
I was hoping that by taking a look at how Windows handles scaling, we might find solutions for squeezed tabs, dialogs, and file menu bars, since Microsoft has done a lot of work on accessibility. However, the results were a mixed bag. At 400% scaling, I came across multiple dialogs that had content off screen and with no way to reach it. With lots of open tabs in Edge, I found that there was no way to scroll through the tabs, but you could use keyboard shortcuts to cycle through tabs. In Microsoft Word, I discovered that the menu bar had a neat feature of putting little left/right arrow buttons at the left and right ends of the file menu bar; this keeps the bar on a single line, as opposed to wrapping the bar to two or more lines; however, at 400% scale, the fine menu bar disappeared completely and I had no idea how to find it, so that seemed less than ideal. I also noticed that in the settings app, the two-panel layout switched to a single panel after a certain point.

So like I said, mixed bag. But we may want to steal the left/right arrows for the menu bar. And we may also want to adopt the approach of switching a two-panel layout to a single panel with a back button to a one-panel home menu.

**Comment by isabela-pf** [comment]
Long overdue, here are some ideas on how to approach the reflowing and content prioritizing needed forJupyterLab to zoom up to 400% without losing content. I’ve been noodling over this at a few different levels, but I think we need to start with thinking about how all the parts interact before spending time on how each detail fits in the many JupyterLab regions. That's why we're operating in a neon, quilted JupyterLab land for now.

I think the core problem from @steff456’s review is the conflict of 
1. Anything greater than 100% zoom limits how much can fit on a screen at once (like character count)
2. JupyterLab’s dense UI
3. Limited responsiveness of JupyterLab UI. What I primarily mean is that setting horizontal scrollbars for overflowing horizontal content, while technically means to access all the UI, are not generally best practice. Especially since many of the scroll bars have small target areas to scroll.

Only 2 and 3 are in our control, so my goal is to get us discussing what UI we want to prioritize as visible by default, what UI is collapsed (but not gone) as default, and how to optimize the responsiveness of these areas. 

## Option 0-3

This approach
- Removes side bar tabs
- Collapses the Main menu area into a single menu button
- Collapses tabs to prioritize the open tab/document name, New Launcher button, and ellipses to expand tabs as a list
- Adds all menus and side bar content to the collapsed main menu area
- Expanding this mega menu lists commands by region and takes up most of the window

![](https://user-images.githubusercontent.com/50221806/186984089-fd8e02a6-f5b0-4860-b72b-f82649c04af4.png)

![](https://user-images.githubusercontent.com/50221806/186984092-444ce07a-28cb-434f-a39d-3cb1505097eb.png)

![](https://user-images.githubusercontent.com/50221806/186984104-27b9dcf0-2232-445d-921b-6d5d04f9f7a5.png)

## Option 0-5

This approach
- Removes side bar tabs
- Collapses the Main menu area into a single menu button
- Collapses tabs to prioritize the open tab/document name, New Launcher button, and ellipses to expand tabs as a list
- Adds all menus and side bar content to the collapsed main menu area
- Expanding this mega menu brings up a command palette with commands by region marked a la table of contents

![](https://user-images.githubusercontent.com/50221806/186984253-fd799db7-3e03-4408-81ff-e3f3957aaf70.png)

![](https://user-images.githubusercontent.com/50221806/186984262-9eb0670f-8430-4908-b6e8-187b36a4004a.png)

## Option 0-9

This approach
- Removes side bar tabs
- Removes the document menu
- Collapses tabs to prioritize the open tab/document name, New Launcher button, and ellipses to expand tabs as a list
- The command palette, which can be found via the View menu or the shortcut, is used to access all else

![](https://user-images.githubusercontent.com/50221806/186984301-f26f4bd4-4f51-4965-95ca-a4f22236e0b8.png)

![](https://user-images.githubusercontent.com/50221806/186984306-c2247ad2-1e7b-4421-b51c-372d52dff676.png)

## Option 0-4

This approach sets the UI based on how the user is interacting with the document. Command mode is for high-level document traversal and edit mode is activated when a user has entered an editable part of a document (ie. when focus in a notebook moves from outside a cell to the editor region of a cell).

When in command mode, this approach

- Removes side bar tabs
- Removes the document menu
- Collapses the Main menu area into a single menu button
- Collapses tabs to prioritize the open tab/document name, New Launcher button, and ellipses to expand tabs as a list
- The command palette, which can be found via the View menu or the shortcut, is available

![](https://user-images.githubusercontent.com/50221806/186984356-c121bea2-ee5a-4551-95c0-998d1f5a51c7.png)

When in edit mode, this approach

- Collapses the Main menu area into a single menu button
- Collapses the side bars into their narrow variations
- The command palette, which can be found via the View menu or the shortcut, is available

![](https://user-images.githubusercontent.com/50221806/186984381-e07e5eec-3f85-4788-9cef-b4ebe114b1c4.png)

## Notes

All of the above are very rough explorations to get discussion started, so they all need more ironing out in order to fill out what the user flow would actually need to be from end to end. Please point out missing gaps, but also know I may not have all the answers yet.

I think option 0-4, while pretty logical and following patterns of other dense, document-based interfaces on small screens, probably isn't viable. It's a totally different experience than JupyterLab unzoomed or at a large screen, and it seems wrong for the UX to be that great. Still, I wanted to provide in case it sparks ideas that are more flexible.

As always, feedback and questions are useful. Thanks! 🌻

**Comment by steff456** [comment]
I also like a lot the option 0-4, I think is the less disruptive one in terms of the current UX in JupyterLab. I think we might need to explore the idea of completely collapsing the main menu, in terms of API flexibility and location of panes. 

I think my main concern with options 0-9, 0-5 and 0-3 is how to manage hiding the sidebars, are they going to be always hidden? How are we going to manage all the options that are inside of them?

**Comment by gabalafou** [comment]
Thanks @isabela-pf for providing the scaffold for us to have more concrete discussions.

I finally got a chance to re-review these proposals.

I also did a deep dive into [WCAG 1.4.10 - Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) aka 400% zoom. I played with Google Docs and Google Colab at 320 CSS px. On desktop, 320 CSS px means start at 1280px width at 100%, then zoom up to 400%. I also played with JupyterLab on my Windows laptop. And I played with it on my iPhone at various levels of zoom and text sizing.

It reminded me of my findings when I scaled up Windows really high and tried to work with Microsoft Word: disappointing, discouraging.

I'm starting to feel that it simply might not be realistic for us to try to rework JupyterLab to meet guideline 1.4.10.

I'm not saying I think it's impossible for us to conform to the guideline. But I want us to ask if it would be worth it. This guideline might be the hardest of all of them to meet with JupyterLab. I have yet to see a classic desktop-style app that strictly conforms at 320 CSS px. Can someone give me a counter example?

Now, the counter argument is that Isabela's proposed layouts could conform to the guideline. But my guess is that Isabela's suggestions will take a **lot** of effort to implement. I'm not sure they can be done in an extension, and if they can't, it would require either a fork of JupyterLab or a lot of changes to the core of JupyterLab. Maybe this is where we need an engineer with lots of JupyterLab experience to give us a quick size estimate.

That being said, my alternative suggestion is that instead of trying to conform at 320 CSS px, we try for analogous reflow conformance at 640 CSS px (aka 200% zoom instead of 400%). We will need to do that anyway to conform to guideline [1.4.4: Resize Text](https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html). This will still give us a lot of work to do, but it seems more tractable to me. 200% zoom is not half the work of 400%; to me, it's more like a tenth or less. That's because I don't think it will require a complete re-think of the existing UI, which is what I consider Isabela's layouts above to be.

Correct me if I'm wrong but I think 320 CSS px was chosen to ensure that web pages would be responsive across a very broad array of mobile devices. Perhaps it's okay for us to say that it's a higher priority for us to focus on the accessibility of the desktop experience (plus tablet).

I dunno, what are all of your thoughts?

**Comment by isabela-pf** [comment]
Following up on the discussion from a few hours ago, we will be moving forward with working on this from 200% zoom. I don't think this changes much from a design perspective in the sense of interaction patterns and needing to free up space for the document.

**Comment by isabela-pf** [comment]
Okay, here’s another idea for review! Please note that this is an opinionated take because I think it’s easier to critique that way. I have some issues with this solution—or at least questions that need more attention—so I’m expecting we’ll end up with a more moderate compromise. 

The major changes:
- This version continues to put the document area into focus at small sizes by removing some of the surrounding UI and adding it to the command palette. 
- The command palette is given a button for easy access, and regions that collapsed have sections to group their commands pinned to the top. 
- Open document tabs are grouped and hidden behind the ellipses, but switching them does not open new browser tabs.
- UI areas originally in the sidebar become their own tab in the document area a la the launcher or settings. UI areas that are reliant on a selection in the main area appear as an overlay to the tab, but this should be used with discretion.

All at once, here’s a basic set of interactions for when users zoom and and how they might navigate when the layout changes.

https://user-images.githubusercontent.com/50221806/193075376-bab8ac9f-f409-410f-8228-238fdf1edcdf.mov

Breaking that down, I’ll explain key points with notes.

<img width="1415" alt="" src="https://user-images.githubusercontent.com/50221806/193075514-4e51cb34-00c7-4eab-ae8c-f2fe2a7e047b.png">

The main menu and both sidebars disappear at 200% and not before. Document name/open tabs are at the top followed by the document menu if the document type has one. Any document specific UI (like the notebook cell toolbar) would stay. 

<img width="1415" alt="" src="https://user-images.githubusercontent.com/50221806/193075577-2444505f-eed5-4364-abe3-f3e854f176be.png">

The command palette stays as an overlapping dialog-like thing. Pinned at the top are sections for easy navigation of the UI areas removed, in this case the main menu and side bars. I do believe this could be open so that extensions could opt in to add themselves as well, so I like the potential for it to scale even if it’s not our main concern. I do think all commands we add should be available in the command palette at all times, but they may not need to be pinned by UI when the main menu and side bars are visible at lower zooms.

<img width="1415" alt="" src="https://user-images.githubusercontent.com/50221806/193075634-df31a30f-12b1-45cd-b950-44178138ad83.png">

Areas from the sidebars that are not document-reliant can open as their own tabs. For example, the file browser can exist totally separate from all open documents. This behavior matches the launcher and settings. Tabs also can be listed for easy switching without relying on the main menu or sidebar options that are less available. I think this should exist for JupyterLab at any zoom level, to be honest.

<img width="1415" alt="" src="https://user-images.githubusercontent.com/50221806/193075713-9bd940bc-dfd7-46ba-babf-f9db0e8a71ef.png">

Areas from the sidebars that are document-reliant can open as some kind of overlap. For example, the table of contents is generated based on the open document selected and can’t work without a document chosen. I don’t love having these two behaviors at once, but it’s what I have for the time being.

<img width="1415" alt="" src="https://user-images.githubusercontent.com/50221806/193075786-e739d7ff-4bda-446f-a34a-c2f977f7d20a.png">

Finally, this shows how the approach can scale to 400% browser zoom. I know 200% is the current focus, but I think it’s worth noting. I also think this can work with different screen orientations.

Questions that might help you get the feedback muscles moving!
1. How do you think this compares with JupyterLab’s current behaviors at 100% zoom and higher?
2. What problems and edge cases can you think of facing with removing areas of the UI? Or with the ones I’ve proposed adding?
4. What technical constraints come to mind?
5. What UI do you think does a good job at this?
6. What parts do you like? Why do you like them. You can do the same for dislikes.

**Comment by gabalafou** [comment]
Thanks @isabela-pf for amazing work, and once again providing the scaffold for us to have concrete conversations.

I have some thoughts that I want to break down into two sections. In the first section I remain a bit abstract. And in the second section, I try to offer thoughts that are more concretely tied to Isabela's idea.

## Translating Dimensions

I think one of the biggest challenges we face with WCAG 1.4.10, or making JupyterLab work at 400% zoom (or 320 CSS px) is that much of the JupyterLab UI was built around the assumption of having enough space to work with in both the x and y dimensions. Let's take the Contextual Help feature for example. You can get to it by right-clicking on a code cell and clicking "Show Contextual Help" near the bottom of the context menu that pops up on right click. That opens up a Contextual Help tab to the side of the notebook document tab. So together, the notebook and contextual help are displayed side-by-side. It looks like this:

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/317883/193377481-39b3f64f-5ecb-4a88-b7b0-a61e62a52bb0.png">

We could keep going like this, pulling up example after example of how the current UI has been built around the assumption of having horizontal space to work with. (We could also pull up examples of the how the current UI has been built around a similar assumption in the y/vertical dimension. For example, in the left sidebar, if the vertical space reduces too far, some of the buttons disappear and you cannot scroll to them.)

But I think that in order to properly meet the 1.4.10 guideline, we will have to translate that UI paradigm from x and y to y and z, by which I mean, we will have to think about pulling things that are laid out horizontally and stacking them vertically, and whenever we can't stack them vertically, we'll have to stack them on top of each other in the z axis (the axis coming out of the screen). Let's take the Contextual Help feature, as an example. Instead of opening it to the side, we could imagine opening it as a modal. As another example, I don't think we've considered taking the sidebars and laying them out horizontally instead of vertically. 

To continue on that last thought, I could imagine getting rid of the top menu bar (File, Edit, View, etc.) and replacing it with a band at the top that acts as a kind of app switcher. The File Browser would be an app, the Open Tabs and Kernels would be an app, as well as the Table of Contents, the Extension Manager, the Debugger, the Property Inspector, the Settings Editor, the Launcher, the Notebook Editor, and so forth.

But I think translating (x, y) to (y, z) is a pretty drastic refactor of the UI, which is why I've had my doubts about being able to meet this WCAG guideline.

## More Concrete Thoughts

That said, I'd like to offer some thoughts on Isabela's idea. I'm not sure how to organize my thoughts, so apologies for the stream of consciousness.

First of all, I think the idea of getting all commands into the command palette is a really smart idea. Whatever route we decide to go down, I think having an always-visible button that opens the command palette is an accessibility feature that we should consider adding to JupyterLab.

Secondly, I still see this as a kind of mobile-first renovation of the JupyterLab UI. On Monday, it might be worth discussing the trade-offs of going down that route versus one that attempts to patch reflow issues in a minimally invasive manner. In a previous conversation that I had one-on-one with Isabela, she pointed out that if we go down the route she proposes, it might save as much work as it creates. Specifically, we won't have to spend time fixing the various side panels if they disappear at 200%. But then again if the aim as suggested by the new 200% mocks above is to pull the side panels out from the side and into document tabs and on-top-of-document overlaps (or modals), then we're back to either having to create new UIs (such as the new open tabs UI imagined above) or having to fix these sub-UIs for narrow screens / high zooms (such as in a table of contents overlap at 200% or greater zoom).

Another thing—I'm sure you've already thought about this—but I'm not sure that it's feasible (from a usability perspective) to take the debugger panel out from its side position and into either a modal or separate tab. I'm not sure (perhaps for lack of imagination) how I would use a debugger without seeing two things at the same time: the code that I'm stepping through and the tools to step through that code. That said, I don't want to imply that I think we should abandon Isabela's proposal just because it may or may not work for one or two extensions that ship with JupyterLab by default. Because overall I think Isabela's designs are the best choice we have right now for the end user experience (over and above conforming to WCAG 1.4.10). The question that's been turning in my head, and for which I don't have a very confident answer, is whether it's feasible—or whether there's a more feasible route.

On a smaller note—the mocks above don't show this—but I think we should get rid of the status bar at 200%.

I hope some of that is helpful! :)
