### ISSUE TITLE
Items needing fixing before another release and announcement

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyterlab-accessible-themes#56]
The following items should be dealt with before an official release and corresponding announcement.

```[tasklist]
### TODO
- [x] Fix broken Jupyter accessibility logo in README - https://github.com/Quansight-Labs/jupyterlab-accessible-themes/pull/58
- [x] Add installation instructions to README (end users)- https://github.com/Quansight-Labs/jupyterlab-accessible-themes/pull/60
- [x] conda-forge feedstock (@gabalafou and I need adding as maintainers, cannot have one single maintainer in a package)
- [ ] https://github.com/Quansight-Labs/jupyterlab-accessible-themes/pull/53
- [x] https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/57 - https://github.com/Quansight-Labs/jupyterlab-accessible-themes/pull/61
- [x] Ensure it requires Python 3.8 or higher - 3.7 reached EOL today and this still requires 3.6 - https://github.com/Quansight-Labs/jupyterlab-accessible-themes/pull/60
- [ ] https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/59
```
